### ISSUE TITLE
a hole in number?

### ISSUE THREAD

**Issue by gnudles** [okellogg/milstd1750tools#3]
if the flt1750.c in function "from_1750eflt"
the following line
  int_mant_hi = (((int) input[0] << 16) | ((int) input[1] & 0xFF00)) >> 8;
 creates a hole in the variable of 8 bit, and that does not seem to be ok.
I think that line code should be 
  int_mant_hi = (((int) input[0] << 8) | ((int) input[1] & 0xFF00)) >> 8;
what do you say?

**Comment by okellogg** [comment]
Thanks for reporting.
I confirm this issue and will be committing the fix shortly.

**Comment by okellogg** [comment]
There were a few more problems with the from_1750flt functions which should be fixed now.

**Comment by gnudles** [comment]
Great! thank you very much... did all of these functions were tested?
